# Generated by Django 2.0.8 on 2018-10-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180913_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('idade', models.CharField(max_length=80)),
                ('cor', models.CharField(max_length=80)),
                ('sexo', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=80)),
                ('Nacionalidade', models.CharField(choices=[('0', 'Brasil'), ('1', 'Argentina'), ('2', 'Paraguai')], max_length=1)),
                ('etinia', models.CharField(choices=[('0', 'Branco'), ('1', 'preto'), ('2', 'Não identificado')], max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date', '-priority', 'event')},
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('0', 'Sem prioridade'), ('1', 'Normal'), ('2', 'Urgente'), ('3', 'Muito Urgente')], max_length=1),
        ),
    ]
